export const ANIMATION_MODE_METEOR = 205;
export const ANIMATION_MODE_BREATHING = 206;
export const ANIMATION_MODE_STACK = 207;
export const ANIMATION_MODE_FLOW = 208;
export const ANIMATION_MODE_WAVE = 209;
export const ANIMATION_MODE_FLASH = 210;
export const ANIMATION_MODE_STATIC = 211;
export const ANIMATION_MODE_CATCHUP = 212;

export const ANIMATION_MODES = {
  [ANIMATION_MODE_STATIC]: 'STATIC',
  [ANIMATION_MODE_METEOR]: 'METEOR',
  [ANIMATION_MODE_BREATHING]: 'BREATHING',
  [ANIMATION_MODE_WAVE]: 'WAVE',
  [ANIMATION_MODE_CATCHUP]: 'CATCHUP',
  [ANIMATION_MODE_STACK]: 'STACK',
  [ANIMATION_MODE_FLASH]: 'FLASH',
  [ANIMATION_MODE_FLOW]: 'FLOW',
};