export const ANIMATION_MODE_METEOR = 'cd';
export const ANIMATION_MODE_BREATHING = 'ce';
export const ANIMATION_MODE_WAVE = 'd1';
export const ANIMATION_MODE_CATCHUP = 'd4';
export const ANIMATION_MODE_STATIC = 'd3';
export const ANIMATION_MODE_STACK = 'cf';
export const ANIMATION_MODE_FLASH = 'd2';
export const ANIMATION_MODE_FLOW = 'd0';

export const ANIMATION_MODES = {
  [ANIMATION_MODE_STATIC]: 'STATIC',
  [ANIMATION_MODE_METEOR]: 'METEOR',
  [ANIMATION_MODE_BREATHING]: 'BREATHING',
  [ANIMATION_MODE_WAVE]: 'WAVE',
  [ANIMATION_MODE_CATCHUP]: 'CATCHUP',
  [ANIMATION_MODE_STACK]: 'STACK',
  [ANIMATION_MODE_FLASH]: 'FLASH',
  [ANIMATION_MODE_FLOW]: 'FLOW',
};